---
title: "Beer Case Study 01"
author: "Team Roman-Greco?"
date: "February 25, 2019"
output: html_document
---

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
## The below code attempts to provide some insights and highlight any relationships between beer and the many factors surrounding it, such as alcohol content and bitterness.

```{r}
library(dplyr)
library(knitr)
library(data.table)
library(doBy)
library(ggplot2)
library(reshape2)

# import Beers.csv data and append column names
beer_df <- read.csv("data\\Beers.csv", sep=",")
names(beer_df) <- c("Beer_Name", "Beer_ID", "ABV", "IBU", "Brewery_ID","Style", "Ounces")

# import Brewery.csv and get number of breweries in each state
brew_df <- read.csv("data\\Breweries.csv", sep=",")
names(brew_df) <- c("Brewery_ID", "Brewery_Name", "Brewery_City","State")

# 1. How many breweries are present in each
table(table(brew_df$State))

# 2. merge datasets and print first and last 6 observations
beer_brew_df <- merge(x = beer_df, y = brew_df, by = "Brewery_ID")
head(beer_brew_df, 6)
tail(beer_brew_df,6)

# 3. report the number of NA's in each column
colSums(is.na(beer_brew_df))

# 4. get median alcohol content (ABV) and international bitterness units (IBU)
median_abv <- summaryBy(ABV ~ State, data = beer_brew_df, FUN=list(median), na.rm=TRUE)
median_ibu <- summaryBy(IBU ~ State, data = beer_brew_df, FUN=list(median), na.rm=TRUE)
median_abv_ibu <- merge(median_abv, median_ibu, by = "State")

ggplot(median_abv_ibu) + 
  geom_col(mapping = aes(x = State, y = ABV.median, fill = State)) + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(median_abv_ibu) + 
  geom_col(mapping = aes(x = State, y = IBU.median, fill = State)) + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1))

# 5. find state with max ABV beer and state with max IBU beer
beer_brew_df$State[which.max(beer_brew_df$ABV)]
beer_brew_df$State[which.max(beer_brew_df$IBU)]


# 6. display summary of ABV
summary(beer_brew_df$ABV)
hist(beer_brew_df$ABV, xlab = "ABV", main="Beer ABV Histogram" )

# 7. Are there any relationships?
ggplot(beer_brew_df) + geom_point(mapping = aes(x = ABV, y = IBU, color = State)) + geom_smooth(method = "lm", aes(x = ABV, y = IBU))

```

